version: '3'

services:
  mangadex-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - default

networks:
  default:
    driver: bridge