version: '3'

services:
  mangadex-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - default
    ports:
      - 9222:9222 # debug port

networks:
  default:
    driver: bridge